export const Fonts = {
  regular: 'Inter-Regular',
  medium: 'Inter-Medium',
  semiBold: 'Inter-SemiBold',
  bold: 'Inter-Bold',
  heading: 'Poppins-SemiBold',
  headingBold: 'Poppins-Bold',
  display: 'Playfair-Bold',
  displayBold: 'Playfair-ExtraBold',
  grotesk: 'SpaceGrotesk-Regular',
  groteskMedium: 'SpaceGrotesk-Medium',
  groteskSemiBold: 'SpaceGrotesk-SemiBold',
  groteskBold: 'SpaceGrotesk-Bold',
  dmSans: 'DMSans-Regular',
  dmSansMedium: 'DMSans-Medium',
  dmSansSemiBold: 'DMSans-SemiBold',
  dmSansBold: 'DMSans-Bold',
};
